.TH XSTARFISH 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
xstarfish \- tiled root window wallpaper generator
.SH SYNOPSIS
.B xstarfish
[
.I options
]
.SH "DESCRIPTION"
XStarfish generates colourful, tiled images using random numbers fed through
mathematical functions and draws them on the background of your desktop. It
does not use source image files, so it can generate its images nearly
forever without running out of material. 

.SH OPTIONS
.TP
\fB-h\fR, \fB--help\fR, \fB--usage\fR
Print the message you're reading now.
.TP
\fB-v\fR, \fB--version\fR
Current version of the program.
.TP
\fB-d\fR, \fB--daemon\fI INTERVAL\fR [\fIUNITS\fR]
Fork off into the background. XStarfish will generate a pattern, sleep for
\fIINTERVAL UNITS\fR, then repeat. Valid units are: \fIseconds\fR,
\fIminutes\fR, \fIhours\fR, \fIdays\fR, \fIweeks\fR. Seconds are the
default interval.
.TP
\fB-p\fR, \fB--pidfile\fR
Creates a \fI$HOME/.xstarfish*\fR file containing the pid of the daemon if
xstarfish is forking into the background.\n"
.TP
\fB--display\fI DISPLAY\fR
Name of the target display.
.TP
\fB-g\fR, \fB--geometry\fI W\fR[x\fIH]\fR
Size of desired image. If you omit the height, a square pattern WxW will be
generated.
.TP
\fB-o\fR, \fB--outfile\fI FILE\fR
Specify an output file. If you use this option, xstarfish will write a png
file instead of setting the X11 desktop.
.TP
\fB-z\fR, \fB--zoom\fI X\fR[x\fIY]\fR
Zoom factor of image.  If you omit the y-scale, a uniform zoom of XxX will
be applied.
.TP
\fB-s\fR, \fB--size\fI SIZE\fR
An approximate size in English. Valid size arguments are \fIsmall\fR,
\fImedium\fR, \fIlarge\fR, \fIfull\fR, and \fIrandom\fR. \fIFull\fR size creates
patterns the exact size of your display's default monitor. \fISmall\fR,
\fImedium\fR, and \fIlarge\fR are randomly sizes at appropriate fractions of
the default monitor size. \fIRandom\fR can be any size from 64x64 up to the
whole monitor. Size always overrides geometry.
.TP
\fB-r\fR, \fB--random\fI SEED\fR
Seed for rand() call - for debugging purposes.
.PP

.SH NOTES
The default size is 256x256. 

.SH AUTHOR
Mars Saxman <mars@redplanetsw.com>
